# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - appstackoverindi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerstackoverindi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c1d314de1cd04e43ab9aebeac12f255c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_26aa784854194840953555fe15cc806d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerstackoverindi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c1d314de1cd04e43ab9aebeac12f255c }}/stackoverflow:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'appstackoverindi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dba00d3776614fc0ab3d26b11f22f58f }}
        images: 'containerstackoverindi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c1d314de1cd04e43ab9aebeac12f255c }}/stackoverflow:${{ github.sha }}'